// <auto-generated />
using System;
using LiturgyGeek.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiturgyGeek.Data.Migrations
{
    [DbContext(typeof(LiturgyGeekContext))]
    partial class LiturgyGeekContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiturgyGeek.Data.Calendar", b =>
                {
                    b.Property<int>("CalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalendarId"));

                    b.Property<string>("CalendarCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CalendarId");

                    b.HasIndex("CalendarCode")
                        .IsUnique();

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("LiturgyGeek.Data.CalendarDefinition", b =>
                {
                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CalendarId");

                    b.ToTable("CalendarDefinitions");
                });

            modelBuilder.Entity("LiturgyGeek.Data.CalendarItem", b =>
                {
                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ChurchRuleId")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OccasionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransferredFrom")
                        .HasColumnType("date");

                    b.HasKey("CalendarId", "Date", "DisplayOrder");

                    b.HasIndex("ChurchRuleId");

                    b.HasIndex("OccasionId");

                    b.ToTable("CalendarItems");
                });

            modelBuilder.Entity("LiturgyGeek.Data.ChurchRule", b =>
                {
                    b.Property<int>("ChurchRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChurchRuleId"));

                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<string>("Elaboration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RuleGroupCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChurchRuleId");

                    b.HasIndex("CalendarId", "RuleGroupCode", "RuleCode")
                        .IsUnique();

                    b.ToTable("ChurchRules");
                });

            modelBuilder.Entity("LiturgyGeek.Data.Occasion", b =>
                {
                    b.Property<int>("OccasionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OccasionId"));

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccasionCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("OccasionId");

                    b.HasIndex("OccasionCode")
                        .IsUnique();

                    b.ToTable("Occasions");
                });

            modelBuilder.Entity("LiturgyGeek.Data.CalendarDefinition", b =>
                {
                    b.HasOne("LiturgyGeek.Data.Calendar", "Calendar")
                        .WithOne("CalendarDefinition")
                        .HasForeignKey("LiturgyGeek.Data.CalendarDefinition", "CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("LiturgyGeek.Data.CalendarItem", b =>
                {
                    b.HasOne("LiturgyGeek.Data.Calendar", "Calendar")
                        .WithMany("CalendarItems")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiturgyGeek.Data.ChurchRule", "ChurchRule")
                        .WithMany("CalendarItems")
                        .HasForeignKey("ChurchRuleId");

                    b.HasOne("LiturgyGeek.Data.Occasion", "Occasion")
                        .WithMany("CalendarItems")
                        .HasForeignKey("OccasionId");

                    b.Navigation("Calendar");

                    b.Navigation("ChurchRule");

                    b.Navigation("Occasion");
                });

            modelBuilder.Entity("LiturgyGeek.Data.ChurchRule", b =>
                {
                    b.HasOne("LiturgyGeek.Data.Calendar", "Calendar")
                        .WithMany("ChurchRules")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("LiturgyGeek.Data.Calendar", b =>
                {
                    b.Navigation("CalendarDefinition");

                    b.Navigation("CalendarItems");

                    b.Navigation("ChurchRules");
                });

            modelBuilder.Entity("LiturgyGeek.Data.ChurchRule", b =>
                {
                    b.Navigation("CalendarItems");
                });

            modelBuilder.Entity("LiturgyGeek.Data.Occasion", b =>
                {
                    b.Navigation("CalendarItems");
                });
#pragma warning restore 612, 618
        }
    }
}
